# Generated by Django 5.1.15 on 2026-07-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quotes", "0001_initial"),
        ("requests", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitivesheet",
            name="best_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="competitivesheet",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitive_sheet",
                to="requests.request",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="requests.request",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="requests.request",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="suppliers.supplier"
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="quotes.quote",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="request_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="requests.requestitem"
            ),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="requests.request",
            ),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="suppliers.supplier"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="invitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotes.rfqinvitation",
            ),
        ),
    ]
