# Generated by Django 5.1.15 on 2026-07-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_body_html_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqinvitation',
            name='reply_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
