# Generated by Django 5.1.15 on 2026-08-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(db_index=True, max_length=50)),
                (
                    "request_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("prompt_preview", models.TextField(blank=True)),
                ("response_preview", models.TextField(blank=True)),
                ("needs_review", models.BooleanField(db_index=True, default=False)),
                ("safety_reason", models.CharField(blank=True, max_length=1000)),
                ("latency_ms", models.IntegerField(default=0)),
                ("status", models.CharField(default="ok", max_length=20)),
                ("source", models.CharField(default="llm", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_email_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
