# Generated by Django 5.1.15 on 2026-07-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supplier',
            name='supplier_active_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='supplier_source_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplieraddress',
            name='supplier_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='suppliercategory',
            name='supplier_cat_idx',
        ),
        migrations.AddField(
            model_name='supplier',
            name='moderation_status',
            field=models.CharField(choices=[('unverified', 'unverified'), ('verified', 'verified'), ('rejected', 'rejected')], default='unverified', max_length=20),
        ),
    ]
