# Generated by Django 5.1.15 on 2026-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_supplier_material_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
