# Generated by Django 5.1.15 on 2026-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_v2_review_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('parsing', 'parsing'), ('parsed', 'parsed'), ('parse_failed', 'parse_failed'), ('confirmed', 'confirmed'), ('matching', 'matching'), ('matched', 'matched'), ('rfq_sent', 'rfq_sent'), ('collecting_quotes', 'collecting_quotes'), ('ready', 'ready'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='draft', max_length=30),
        ),
    ]
