# Generated by Django 5.1.15 on 2026-07-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0003_requestitem_material_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=300, unique=True)),
                ("canonical_name", models.CharField(blank=True, max_length=300)),
                (
                    "material_type",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("category_hint", models.CharField(blank=True, max_length=100)),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("search_queries", models.JSONField(blank=True, default=list)),
                ("supplier_hints", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "material_profiles",
            },
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("parsing", "parsing"),
                    ("confirmed", "confirmed"),
                    ("matching", "matching"),
                    ("matched", "matched"),
                    ("rfq_sent", "rfq_sent"),
                    ("rfq_failed", "rfq_failed"),
                    ("collecting_quotes", "collecting_quotes"),
                    ("ready", "ready"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
