# Generated by Django 5.1.15 on 2026-07-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0004_materialprofile_alter_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestitem",
            name="clarification_question",
            field=models.TextField(blank=True),
        ),
    ]
