# Generated by Django 5.1.15 on 2026-08-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0006_request_match_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("parsing", "parsing"),
                    ("parsed", "parsed"),
                    ("confirmed", "confirmed"),
                    ("matching", "matching"),
                    ("matched", "matched"),
                    ("rfq_sent", "rfq_sent"),
                    ("rfq_failed", "rfq_failed"),
                    ("collecting_quotes", "collecting_quotes"),
                    ("ready", "ready"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
