# Generated by Django 5.1.15 on 2026-08-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_status_fix'),
        ('requests', '0007_alter_request_status'),
    ]

    operations = [
    ]
