# Generated by Django 5.1.15 on 2026-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_v2_review_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='material_type',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
