# Generated by Django 5.1.15 on 2026-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('manufacturer', 'manufacturer'), ('dealer', 'dealer'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='supplier_type',
            field=models.CharField(choices=[('manufacturer', 'manufacturer'), ('dealer', 'dealer'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
