# Generated by Django 5.1.15 on 2026-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='source',
            field=models.CharField(choices=[('seed', 'seed'), ('llm', 'llm'), ('web', 'web'), ('manual', 'manual')], default='seed', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='source',
            field=models.CharField(choices=[('seed', 'seed'), ('llm', 'llm'), ('web', 'web'), ('manual', 'manual')], default='seed', max_length=20),
        ),
    ]
