# Generated by Django 5.1.15 on 2026-07-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='source',
            field=models.CharField(choices=[('seed', 'seed'), ('llm', 'llm'), ('web', 'web'), ('2gis', '2gis'), ('dadata', 'dadata'), ('manual', 'manual')], default='seed', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='source',
            field=models.CharField(choices=[('seed', 'seed'), ('llm', 'llm'), ('web', 'web'), ('2gis', '2gis'), ('dadata', 'dadata'), ('manual', 'manual')], default='seed', max_length=20),
        ),
    ]
