# Generated by Django 5.1.15 on 2026-07-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_request_status'),
        ('suppliers', '0004_supplier_source_dadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieraddress',
            name='source',
        ),
        migrations.RemoveField(
            model_name='supplieraddress',
            name='supplier_type',
        ),
        migrations.AddField(
            model_name='supplier',
            name='moderation_status',
            field=models.CharField(choices=[('unverified', 'На проверке'), ('verified', 'Подтверждён'), ('rejected', 'Отклонён')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='legal_name',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='source',
            field=models.CharField(choices=[('seed', 'Seed'), ('llm', 'LLM'), ('web', 'Web'), ('2gis', '2GIS'), ('dadata', 'DaData'), ('manual', 'Вручную')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('manufacturer', 'Производитель'), ('dealer', 'Дилер'), ('unknown', 'Неизвестно')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='city',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('supplier', 'category')},
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active', 'moderation_status', 'supplier_type'], name='suppliers_is_acti_d68915_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraddress',
            index=models.Index(fields=['city', 'is_active'], name='supplier_ad_city_5a7f23_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraddress',
            index=models.Index(fields=['latitude', 'longitude', 'is_active'], name='supplier_ad_latitud_07b619_idx'),
        ),
    ]
