# Generated by Django 5.1.15 on 2026-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_v2_review_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='material_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
