# Generated by Django 5.1.15 on 2026-07-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at']},
        ),
    ]
