# Generated by Django 5.1.15 on 2026-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
