# Generated by Django 5.1.15 on 2026-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_add_reply_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqinvitation",
            name="reminder_24h_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="reminder_2h_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
